# https://gohugo.io/getting-started/configuration/#configure-dates
date = ["publishdate", "date", "lastmod"]                             # :default = ["date", "publishDate", "lastmod"]
expirydate = ["expirydate"]                                           # :default = ["expiryDate"]
lastmod = ["lastmod", ":git", ":fileModTime", "publishdate", "date"]  # :default = [":git", "lastmod", "date", "publishDate"]
publishdate = ["publishdate", "date"]                                 # :default = ["publishDate", "date"]
