### See: https://gohugo.io/about/security-model/

enableInlineShortcodes = false                          # disabled for security reasons as per Hugo documentation

[exec]
  allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$']
  osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[funcs]
  getenv = ['^HUGO_']

[http]
  methods = ['(?i)GET|POST']
  urls = ['.*']
